In [37]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Subset


import numpy as np
import pandas as pd

import re
import nltk

from transformers import (
    MarianMTModel,
    MarianTokenizer,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    DataCollatorForSeq2Seq
)

from datasets import Dataset

model_name = "Helsinki-NLP/opus-mt-ar-en"
model = MarianMTModel.from_pretrained(model_name)
tokenizer = MarianTokenizer.from_pretrained(model_name)
print("loaded model:", model_name)

# tokenizer
# tokenizer = nltk.TweetTokenizer()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("runnig on", device)

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

loaded model: Helsinki-NLP/opus-mt-ar-en
runnig on cuda

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:176: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

In [25]:
text_file = r"/content/ara.txt"
columns = ["English", "Arabic", "Attribution"]
# header and names prevent the dataframe from starting with data
data = pd.read_csv(text_file, delimiter='\t', header=None, names=columns)

working_data = data.copy()
working_data.head()

  English          Arabic                                        Attribution
0     Hi.         مرحبًا.  CC-BY 2.0 (France) Attribution: tatoeba.org #5...
1    Run!           اركض!  CC-BY 2.0 (France) Attribution: tatoeba.org #9...
2   Duck!      اخفض رأسك!  CC-BY 2.0 (France) Attribution: tatoeba.org #2...
3   Duck!     اخفضي رأسك!  CC-BY 2.0 (France) Attribution: tatoeba.org #2...
4   Duck!  اخفضوا رؤوسكم!  CC-BY 2.0 (France) Attribution: tatoeba.org #2...

In [6]:
class TranslationDataset(Dataset):
    def __init__(self, data, tokenizer, stopwords):
        super(TranslationDataset, self).__init__()
        self.data = data

        #######################
        # English Preprocessing
        #######################

        self.data['cleaned_english'] = self.data['English'].apply(self.clean_data)
        self.data['tokenized_english'] = self.data['cleaned_english'].apply(lambda x: self.tokenize_text(x, tokenizer, stopwords))

        # get longest sequence
        self.longest_seq = self.get_longest_seq(list(self.data['tokenized_english'].values))

        # pad tokens
        self.data["padded_tokens"] = self.data['tokenized_english'].apply(lambda x: self.pad_tokens(x, self.longest_seq))

        # get word2idx
        self.word2idx = self.get_word2idx(list(self.data['padded_tokens'].values))

        # get idx2word
        self.idx2word = {idx : word for idx, word in enumerate(self.word2idx)}

        # get indices
        self.data['indices'] = self.data['padded_tokens'].apply(lambda x: self.get_indices(x, self.word2idx))

        ######################
        # Arabic Preprocessing
        ######################

        # clean arabic data
        self.data['cleaned_arabic'] = self.data['Arabic'].apply(self.clean_data)

        # tokenize arabic
        self.data['tokenized_arabic'] = self.data['cleaned_arabic'].apply(lambda x: self.tokenize_text(x, tokenizer, stopwords))

        # get longest sequence
        self.longest_seq_arab = self.get_longest_seq(list(self.data['tokenized_arabic'].values))

        # pad tokens
        self.data["padded_tokens_arabic"] = self.data['tokenized_arabic'].apply(lambda x: self.pad_tokens(x, self.longest_seq_arab))

        # get word2idx
        self.word2idx_arabic = self.get_word2idx(list(self.data['padded_tokens_arabic'].values))

        # get idx2word
        self.idx2word_arabic = {idx : word for idx, word in enumerate(self.word2idx_arabic)}

        # get indices
        self.data['indices_arabic'] = self.data['padded_tokens_arabic'].apply(lambda x: self.get_indices(x, self.word2idx_arabic))



    def clean_data(self, text):
        """
        cleans data and prepares it for tokenization
        Args:
            data: input_data (pd.DataFrame)
            tokenizer: nltk.tokenizer
        Returns:
            clean_data: List(List)
        """
        lower = text.lower()
        clean_text = re.sub(r'!"#$%&\'()*+-/:;<=>?@[\\]^_`{|}~', '', lower)
        return '<SOS>' + clean_text + '<EOS>'

    def tokenize_text(self, text, tokenizer, stopwords):
        """
        break texts into tokens
        Args:
            text (str): text to tokenize
            tokenizer (nltk.tokenizer): to convert texts into tokens
            stopwords (nltk.corpus.stopwords.words): list of words to not include in vocab

        Return:
            tokens (List): a list of tokens
        """
        tokens = tokenizer.tokenize(text)
        tokens = [token for token in tokens if token not in stopwords]
        return tokens

    def get_longest_seq(self, tokens):
        """
        Args:
            tokens: list of tokens
        Returns:
        longest_seq (int): longest sequence in datset
        """

        longest_seq = 0

        for token in tokens:
            if len(token) > longest_seq:
                longest_seq = len(token)

        return longest_seq

    def pad_tokens(self, tokens, max_len):
        """
        To make sure all tokens havethe same length
        Args:
            tokens: list of tokens
        Returns:
            padded_tokens (List): list of padded tokens
        """
        if len(tokens) < max_len:
            return tokens + ['<PAD>' for _ in range(max_len - len(tokens))]
        return tokens

    def get_word2idx(self, all_tokens):
        word2idx ={
            '<SOS>' : 0,
            '<EOS>' : 1,
            '<PAD>' : 2,
            '<UNK>': 3,
        }

        for tokens in all_tokens:
            for token in tokens:
                if token not in word2idx:
                    word2idx[token] = len(word2idx)

        return word2idx

    def get_indices(self, tokens, vocab):
        indices = []
        for token in tokens:
                indices.append(vocab.get(token, vocab['<UNK>']))
        return indices

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):

        if torch.is_tensor(idx):
            idx = idx.tolist()

        english_indices = self.data.iloc[idx]['indices']
        arabic_indices = self.data.iloc[idx]['indices_arabic']

        return torch.tensor(english_indices, dtype=torch.long), torch.tensor(arabic_indices, dtype=torch.long)

In [ ]:
tokenizer = nltk.TweetTokenizer()
stopwords = nltk.corpus.stopwords.words('english')

dataset = TranslationDataset(data, tokenizer, stopwords)
indices = torch.randperm(len(dataset))

train_size = int(0.7*len(indices))
train_dataset = Subset(dataset, indices=indices[:train_size])
val_dataset = Subset(dataset, indices=indices[train_size:])

batch_size=64
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_dataloader = DataLoader(val_dataset, batch_size=batch_size, shuffle=True)

I found a translation model on huggingface, ill just learn to finetune that instead of training my own

In [33]:
data_copy = data[['English', 'Arabic']]
translation_data = []
for index, row in data_copy.iterrows():
  trans_pair = {"translation": {"ar": row['Arabic'], "en" : row['English']}}
  translation_data.append(trans_pair)

dataset = Dataset.from_list(translation_data)

# split dataset into train and validation sets
dataset = dataset.train_test_split(test_size=0.2)
train_dataset = dataset["train"]
test_dataset = dataset["test"]

# tokenize data
max_input_length = 128
max_output_length = 128

def process_function(examples):
  # extract inputs and targets
  inputs = [ex['ar'] for ex in examples['translation']]
  targets = [ex['en'] for ex in examples['translation']]

  # tokenize input (arabic)
  model_inputs = tokenizer(inputs, max_length=max_input_length, truncation=True)

  # tokenize output (english)
  labels = tokenizer(targets, max_length=max_output_length, truncation=True)

  model_inputs['labels'] = labels['input_ids']
  return model_inputs

tokenized_train = train_dataset.map(process_function, batched=True)
tokenized_test = test_dataset.map(process_function, batched=True)

Map:   0%|          | 0/10018 [00:00<?, ? examples/s]

Map:   0%|          | 0/2505 [00:00<?, ? examples/s]

In [38]:
# data collator dynamically pads the sentences to the longest sentence in the current batch
data_collator = DataCollatorForSeq2Seq(tokenizer, model=model)

In [45]:
training_args = Seq2SeqTrainingArguments(
    output_dir="/ar-en-finetuned-model",
    eval_strategy='epoch',
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    weight_decay=0.01,
    save_total_limit=3,
    num_train_epochs=3,
    predict_with_generate=True,
    fp16=torch.cuda.is_available()
)

In [49]:
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_test,
    data_collator=data_collator
)

In [50]:
print("start training >>>")
trainer.train()

# save model
trainer.save_model("./translation_model")
print(f"model fine-tuning complete and saved!")

start training >>>

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

model fine-tuning complete and saved!

In [ ]:
# Load your fine-tuned model from the local folder
finetuned_tokenizer = MarianTokenizer.from_pretrained("./translation_model")
finetCuned_model = MarianMTModel.from_pretrained("./translation_model")

Loading weights:   0%|          | 0/256 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Jesus loves you.

In [ ]:

# Translate text with it
text = "يسوع يحبك"
inputs = finetuned_tokenizer(text, return_tensors="pt")
translated = finetuned_model.generate(**inputs)
print(finetuned_tokenizer.decode(translated[0], skip_special_tokens=True))

Jesus loves you.